export const HOTELIST = [
    {
        "hotelImage": "../../../assets/images/download.jpg",
        "hotelName": "Orritel",
        "rating": 3,
        "address": "Pune, 14.8 km to City Centre",
        "discountValue": "-29%",
        "oldRate": "1,999",
        "newRate": "1,399",
    },
    {
        "hotelImage": "../../../assets/images/download.jpg",
        "hotelName": "FabHotel Magnus Star Koregaon Park Opens in new window",
        "rating": 4,
        "address": "Viman nagar Pune, 6 km to City Centre",
        "discountValue": "-10%",
        "oldRate": "11,672",
        "newRate": "10,557",
    },
    {
        "hotelImage": "../../../assets/images/download.jpg",
        "hotelName": "Apartment with Wi-Fi in Pune, by GuestHouser ",
        "rating": 0,
        "address": "Aundh Pune, 14.8 km to City Centre",
        "discountValue": "-29%",
        "oldRate": "1,999",
        "newRate": "1,399",
    },
    {
        "hotelImage": "../../../assets/images/download.jpg",
        "hotelName": "Treebo Trend Regency",
        "rating": 3,
        "address": "Pune, 2.7 km to City Centre",
        "discountValue": "-29%",
        "oldRate": "9,203",
        "newRate": "8,766",
    },
    {
        "hotelImage": "../../../assets/images/download.jpg",
        "hotelName": "Orritel",
        "rating": 3,
        "address": "Pune, 14.8 km to City Centre",
        "discountValue": "-29%",
        "oldRate": "1,999",
        "newRate": "1,399",
    },
    {
        "hotelImage": "../../../assets/images/download.jpg",
        "hotelName": "Orritel",
        "rating": 3,
        "address": "Pune, 14.8 km to City Centre",
        "discountValue": "-29%",
        "oldRate": "1,999",
        "newRate": "1,399",
    },
    {
        "hotelImage": "../../../assets/images/download.jpg",
        "hotelName": "Orritel",
        "rating": 3,
        "address": "Pune, 14.8 km to City Centre",
        "discountValue": "-29%",
        "oldRate": "1,999",
        "newRate": "1,399",
    },
    {
        "hotelImage": "../../../assets/images/download.jpg",
        "hotelName": "Orritel",
        "rating": 3,
        "address": "Pune, 14.8 km to City Centre",
        "discountValue": "-29%",
        "oldRate": "1,999",
        "newRate": "1,399",
    },
    {
        "hotelImage": "../../../assets/images/download.jpg",
        "hotelName": "Orritel",
        "rating": 3,
        "address": "Pune, 14.8 km to City Centre",
        "discountValue": "-29%",
        "oldRate": "1,999",
        "newRate": "1,399",
    },
    {
        "hotelImage": "../../../assets/images/download.jpg",
        "hotelName": "Orritel",
        "rating": 3,
        "address": "Pune, 14.8 km to City Centre",
        "discountValue": "-29%",
        "oldRate": "1,999",
        "newRate": "1,399",
    },
]